# Generated by Django 3.2.6 on 2021-08-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rota',
            new_name='Shift',
        ),
    ]
