# Generated by Django 3.2.6 on 2021-08-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_rota_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='absence',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='absence',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
    ]
