# Generated by Django 3.2.6 on 2021-08-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_shift_day_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='day_of_the_week',
            field=models.IntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')], verbose_name='Dzień tygodnia'),
        ),
    ]
